### ISSUE TITLE
Empty arrays

### ISSUE THREAD

**Issue by panchicore** [lensesio/landoop-avro4s-ui#2]
To AVRO:

```
{"a":[]}
```

The output is being kind of server error or empty response.

Should generate _(not sure if it should assume this way, but the empty array is being explicit in the example)_:

```
{
  "type" : "record",
  "name" : "MyClass",
 "fields": [
    {"name": "a", "type": {"type": "array", "items": "string"}, "default": []}
 ]
}
```

**Comment by Antwnis** [comment]
Hi @panchicore In your example `{"a":[]}` is indeed an array

How can one assume that it's an array of **Strings**  ? Maybe it's an array of **Integers** or **Long** or any other type.. Also the `"default"` is an assumption

The above is the reason - you are getting an empty response, as avro4s is avoiding making assumptions 

Feel free to re-open if the above answer is not satisfactory

**Comment by panchicore** [comment]
Hi @Antwnis, it's curious because:

`{"a":null}`

resolves:

```
{
  "type" : "record",
  "name" : "MyClass",
  "namespace" : "com.test.avro",
  "fields" : [ {
    "name" : "a",
    "type" : [ "string", "null" ]
  } ]
}
```

anyways, it would be great to receive the validation exception instead to output a blank response?
